DS241 Project
Liam Durkin
11/29/2022

If you don't have the package installed, do it here
```{r}
install.packages("lehdr")
```

```{r}
library(lehdr)
library(dplyr)
#library(devtools)
```

```{r}
states = c("or", "ri")
years = c(2013, 2014)

#grab_lodes info: https://rdrr.io/github/jamgreen/lehdR/man/grab_lodes.html
# state - US abbreviation in lowercase
# year - year of the lodes data
# lodes_type - origin-destination ("od", home and destination), residential association ("rac", job totals of worker home), or workplace association ("wac", job totals of worker job)
# segment - segment of workforce, see website
# agg_geo - aggregate to a geography other than census block ("bg" block group, "tract", "county", or "state")
# state_part - "main" or "aux"
# download dir - directory where lodes table will be downloaded
# use_cache - whether or not file has already been downloaded, defaults to FALSE


lode_data <- grab_lodes(state = "dc", year = 2019, lodes_type = "od", job_type = "JT00",
           segment = "S000", state_part = "main", agg_geo = "bg")

head(lode_data)
```

