---
title: "bike_stuff"
author: "Joseph White"
date: "10/27/22"
output: github_document
---

##Load Packages
```{r}
library(tidyverse) 
library(dsbox)
library(lubridate)
library(ggplot2)
library(janitor)
library(here)

install.packages("gbfs")
library(gbfs)
```

```{r}
bike_data <- read_csv("202209-capitalbikeshare-tripdata.csv") %>% clean_names()
```

```{r}
bike_data_m <- bike_data %>%
  filter(member_casual == "member")

bike_data_c <- bike_data %>%
  filter(member_casual == "casual")

ggplot(bike_data_m, mapping = aes(x = start_lng, y = start_lat)) +
  geom_point()

ggplot(bike_data_c, mapping = aes(x = start_lng, y = start_lat)) +
  geom_point()
```
## bikes out per day ish
```{r}
bike_data_use <- bike_data %>% 
  select(started_at) %>%
  separate(started_at, c("date", "time"), " ") %>%
  separate(time, c("hour","minute","second"), ":") %>%
  mutate(minu = as.numeric(hour)*60 + as.numeric(minute))%>%
  separate(date, c("year","month","day"), "-") %>%
  filter(day == "01")
```


# plot
```{r}
ggplot(bike_data_use, aes(x= minu)) + geom_dotplot(binwidth = 5)
```

## class work
```{r}
bike_data_class <- bike_data %>%
  mutate(duration = (ended_at - started_at)/60,
         hour_of_day = hour(started_at),
         day_of_week = wday(started_at, label = T))
```

## visu
```{r}
bike_data_class %>%
  filter(duration < 100, duration > 0) %>%
  ggplot(aes(x = duration)) + geom_histogram(bins = 300) + facet_wrap(~day_of_week)
```

## riders v time
```{r}
df <- bike_data_class %>%
 # filter(mday(started_at) == 3) %>%
  filter(month(started_at)==9, month(ended_at)==9) %>%
  select(start = started_at, end = ended_at) %>%
  pivot_longer(start:end) %>%
  arrange(value) %>%
  mutate(nu = case_when(name == "start" ~ 1, name == "end" ~ -1)) %>%
  mutate(bike_out = cumsum(nu)) 
```

## plot
```{r}
ggplot(df, aes(value, bike_out)) + geom_step() + facet_wrap(~mday(value), scales = "free_x", ncol = 7)
```

## rider type
```{r}
df1 <- bike_data_class %>%
  filter(month(started_at)==9, month(ended_at)==9) %>%
  select(member_casual, start = started_at, end = ended_at) %>%
  pivot_longer(start:end) %>%
  arrange(value) %>%
  mutate(nu = case_when(name == "start" ~ 1, name == "end" ~ -1)) %>%
  group_by(member_casual) %>%
  mutate(bike_out = cumsum(nu))
```

## plot
```{r}
ggplot(df1, aes(value, nu, color = member_casual)) + geom_step() +
  facet_wrap(~mday(value),scales = "free_x",ncol = 7)
```

## 11/3/22
```{r}
df_2 <- bike_data %>%
  filter(month(started_at)==9, month(ended_at)==9) %>%
  select(started_at, ended_at, member_casual) %>% 
  mutate(int = as.numeric(started_at - ended_at)  * -1 / 60)
```

## plot
```{r}
abc <- ggplot( df_2, aes(int)) + geom_histogram() + facet_wrap(~mday(started_at),scales = "free_x",ncol = 7)
abc + xlim(0, 100)
```

##11/4/22 Class Work

## using gbfs
```{r}
station_info <- get_station_information("https://gbfs.biketownpdx.com/gbfs/gbfs.json")
station_status <- get_station_status("https://gbfs.biketownpdx.com/gbfs/gbfs.json")

station <- merge(station_info, station_status, "station_id") %>%
  select(station_id, address, name, lon, lat)

```

##Explore this

##Data Load
```{r}
df_cities=get_gbfs_cities()
```

##Looking up in the df_cities list, found capital bikeshare code as "cabi".

```{r}
cabi_free=get_free_bike_status("cabi")
```

```{r}
cabi_free %>% ggplot(aes(x=lon,y=lat)) + geom_point()
```

```{r}
get_free_bike_status("cabi") %>% ggplot(aes(x=lon,y=lat)) + geom_point()
```

```{r}
df_cities=get_gbfs_cities()
```

```{r}
cabidf_stations = get_station_information("cabi")
```

```{r}
cabidf_stations %>% ggplot(aes(x=lon, y=lat)) + geom_point()
```


